begin;

create table if not exists public.audit_logs (
    id bigint generated by default as identity primary key,
    admin_id uuid references public.profiles (id) on delete set null,
    patient_id uuid not null references public.profiles (id) on delete cascade,
    action text not null,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists audit_logs_patient_id_created_at_idx
    on public.audit_logs (patient_id, created_at desc);

create index if not exists audit_logs_admin_id_created_at_idx
    on public.audit_logs (admin_id, created_at desc);

alter table public.audit_logs enable row level security;
alter table public.audit_logs force row level security;

DROP POLICY IF EXISTS audit_logs_select_policy ON public.audit_logs;
create policy audit_logs_select_policy
on public.audit_logs
for select
using (public.is_admin());

DROP POLICY IF EXISTS audit_logs_insert_policy ON public.audit_logs;
create policy audit_logs_insert_policy
on public.audit_logs
for insert
with check (public.is_admin());

commit;
